version: '3.8'

services:
  lead-generator-mcp:
    build: .
    ports:
      - "8086:8086"
    environment:
      - AUTH_TOKEN=mgnQZv9-QwIc2qTvDIr6lay-6fFMqSpcS4B-kRemNV8
      - MY_NUMBER=919998881729
      - SERPER_API_KEY=${SERPER_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CSV_TTL_SECONDS=3600
      - MAX_CONCURRENCY=4
      - BASE_URL=http://localhost:8086
    restart: unless-stopped